### ISSUE TITLE
Closing of Renovate PRs if they are not a success?

### ISSUE THREAD

**Issue by jamesbraza** [mmkal/runovate#3]
In my repo, I have CI that gets run and PR merge requires unit tests to pass. Let's say a particular dependency upgrade breaks CI, so Renovate's automerge into `deps-branch` doesn't take place.

In that case, what do you think of having this GitHub Action auto-close the failed PRs?

**Comment by mmkal** [comment]
Unless I'm misunderstanding, that would not be something I would want. I want to see which dependency upgrades are going to cause a problem and require human intervention. The successful ones can just roll up quietly and merge en masse. 

Also curious where you're using this from because as of right now this is undocumented/experimental.

**Comment by jamesbraza** [comment]
> Unless I'm misunderstanding, that would not be something I would want. I want to see which dependency upgrades are going to cause a problem and require human intervention. The successful ones can just roll up quietly and merge en masse.

Sounds good, makes sense. I will close this one out 👌 

> Also curious where you're using this

Repos at FutureHouse like https://github.com/Future-House/paper-qa (and private repos we'll make public soon). I want to use this GitHub Action to combine:
- Lock file maintenance
- Minor dependency upgrades
- `pre-commit autoupdate`s
